# Generated by Django 3.2.4 on 2021-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210626_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Rejected'), (3, 'Approved')], default=1),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
