# Generated by Django 3.2.4 on 2021-06-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210627_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
